addReviewers: true
addAssignees: true

reviewers:
  - Josy-coder
  - benconte

filterLabels:
  include:
    - '*'

numberOfAssignees: 1
numberOfReviewers: 1

useReviewGroups: true
reviewGroups:
  groupA:
    - Josy-coder
  groupB:
    - benconte

useAssigneeGroups: true
assigneeGroups:
  groupA:
    - benconte
  groupB:
    - Josy-coder