// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: team_members.sql

package models

import (
	"context"
)


const getTeamMember = `-- name: GetTeamMember :one
SELECT teamid, studentid FROM TeamMembers WHERE TeamID = $1 AND StudentID = $2
`

type GetTeamMemberParams struct {
	Teamid    int32 `json:"teamid"`
	Studentid int32 `json:"studentid"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (Teammember, error) {
	row := q.db.QueryRowContext(ctx, getTeamMember, arg.Teamid, arg.Studentid)
	var i Teammember
	err := row.Scan(&i.Teamid, &i.Studentid)
	return i, err
}



const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM TeamMembers WHERE TeamID = $1 AND StudentID = $2
`

type RemoveTeamMemberParams struct {
	Teamid    int32 `json:"teamid"`
	Studentid int32 `json:"studentid"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.Teamid, arg.Studentid)
	return err
}
