apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      nodeSelector:
        kubernetes.io/hostname: lke252359-403035-18d2c9e90000
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: wait-for-envoy
        image: busybox
        command: ['sh', '-c', 'until nc -z envoy 80; do echo waiting for envoy; sleep 2; done;']
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: backend
        image: josycoder/irankhub:backend-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8080
          name: grpc
      imagePullSecrets:
      - name: regcred