apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  # Changed from 1 to 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      nodeSelector:
        kubernetes.io/hostname: lke252359-403035-18d2c9e90000
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: wait-for-envoy
          image: busybox
          command: ['sh', '-c', 'until nc -z envoy 80; do echo waiting for envoy; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: backend
          image: josycoder/irankhub:backend-latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "3Gi"
              cpu: "1200m"
              ephemeral-storage: "40Gi"
            limits:
              memory: "4Gi"
              cpu: "1800m"
              ephemeral-storage: "50Gi"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: TOKEN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: token-keys
                  key: TOKEN_PUBLIC_KEY
            - name: TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: token-keys
                  key: TOKEN_PRIVATE_KEY
            - name: MAX_PROCS
              value: "2"         # Keep as 2 since we have 2 replicas
            - name: DB_MAX_CONNS
              value: "40"        # Keep as 40 per replica
            - name: DB_MIN_CONNS
              value: "10"        # Keep as 10 per replica
          readinessProbe:
            tcpSocket:           # Changed back to tcpSocket as requested
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:           # Changed back to tcpSocket as requested
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              name: grpc
      imagePullSecrets:
        - name: regcred