apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      nodeSelector:
        kubernetes.io/hostname: lke246307-390838-5911832b0000
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.30-latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 10000
          hostPort: 10000
        - containerPort: 9901
          hostPort: 9901
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  type: ClusterIP
  selector:
    app: envoy
  ports:
    - port: 10000
      targetPort: 10000
      name: http
    - port: 9901
      targetPort: 9901
      name: admin