apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: lke252359-403034-55c1a49e0000
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          resources:
            requests:
              memory: "512Mi"  # Doubled from 256Mi
              cpu: "400m"      # Doubled from 200m
            limits:
              memory: "1Gi"    # Doubled from 512Mi
              cpu: "800m"      # Doubled from 400m
          ports:
            - containerPort: 80
              hostPort: 80     # Kept hostPort since we're using 1 replica
              protocol: TCP
            - containerPort: 443
              hostPort: 443    # Kept hostPort since we're using 1 replica
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: certbot-webroot
              mountPath: /var/www/certbot
            - name: ssl-certs
              mountPath: /etc/letsencrypt/live/backend.debaterwanda.org/
              readOnly: true
            - name: nginx-temp
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          # Added performance optimizations
          env:
            - name: NGINX_WORKER_PROCESSES
              value: "auto"
            - name: NGINX_WORKER_CONNECTIONS
              value: "8192"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: certbot-webroot
          emptyDir: {}
        - name: ssl-certs
          secret:
            secretName: ssl-cert-secret
            items:
              - key: tls.crt
                path: fullchain.pem
              - key: tls.key
                path: privkey.pem
              - key: chain.pem
                path: chain.pem
        - name: nginx-temp
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP