apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: lke252359-403035-18d2c9e90000
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:13-alpine
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "48Gi"
          limits:
            memory: "2Gi"
            cpu: "1"
            ephemeral-storage: "64Gi"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      - name: storage-metrics
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            USED=$(df -B1 /data/postgres | tail -1 | awk '{print $3}')
            TOTAL=$(df -B1 /data/postgres | tail -1 | awk '{print $2}')
            echo "{\"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"used_bytes\": $USED, \"total_bytes\": $TOTAL}" >> /metrics/storage.log
            tail -n 1000 /metrics/storage.log > /metrics/storage.log.tmp && mv /metrics/storage.log.tmp /metrics/storage.log
            sleep 60
          done
        volumeMounts:
        - name: postgres-storage
          mountPath: /data
          subPath: postgres
        - name: metrics
          mountPath: /metrics
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
      - name: metrics
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "linode-block-storage"
      resources:
        requests:
          storage: 30Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432