apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        kubernetes.io/hostname: lke252359-403034-55c1a49e0000
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            /docker-entrypoint-initdb.d/init-rabbitmq.sh &
            docker-entrypoint.sh rabbitmq-server
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "20Gi"
          limits:
            memory: "2Gi"
            cpu: "1"
            ephemeral-storage: "24Gi"
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init-rabbitmq.sh
          subPath: init-rabbitmq.sh
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 30
          periodSeconds: 20
      - name: storage-metrics
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            USED=$(df -B1 /data | tail -1 | awk '{print $3}')
            TOTAL=$(df -B1 /data | tail -1 | awk '{print $2}')
            echo "{\"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"used_bytes\": $USED, \"total_bytes\": $TOTAL}" >> /metrics/storage.log
            tail -n 1000 /metrics/storage.log > /metrics/storage.log.tmp && mv /metrics/storage.log.tmp /metrics/storage.log
            sleep 60
          done
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /data
        - name: metrics
          mountPath: /metrics
      volumes:
      - name: init-script
        configMap:
          name: rabbitmq-init-script
          defaultMode: 0755
      - name: metrics
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "linode-block-storage"
      resources:
        requests:
          storage: 30Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management