apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        kubernetes.io/hostname: lke252359-403034-55c1a49e0000
      terminationGracePeriodSeconds: 10
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management-alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              /docker-entrypoint-initdb.d/init-rabbitmq.sh &
              docker-entrypoint.sh rabbitmq-server
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "600m"
            limits:
              memory: "2.5Gi"
              cpu: "1"
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            # Performance optimizations for message storage
            - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
              value: "0.7"  # Allow using more memory (70% of limit)
            - name: RABBITMQ_DISK_FREE_LIMIT
              value: "5GB"  # Increased disk free limit
            # Message persistence settings
            - name: RABBITMQ_MNESIA_BASE
              value: "/var/lib/rabbitmq/mnesia"
            # Enable message persistence
            - name: RABBITMQ_PLUGINS_DIR
              value: "/plugins:/usr/lib/rabbitmq/plugins"
            - name: RABBITMQ_ENABLED_PLUGINS_FILE
              value: "/etc/rabbitmq/enabled_plugins"
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-rabbitmq.sh
              subPath: init-rabbitmq.sh
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: enabled-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: init-script
          configMap:
            name: rabbitmq-init-script
            defaultMode: 0755
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
            defaultMode: 0644
        - name: enabled-plugins
          configMap:
            name: rabbitmq-plugins
            defaultMode: 0644
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "linode-block-storage"
        resources:
          requests:
            storage: 50Gi