name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployments/docker/backend.Dockerfile
        push: true
        tags: josy-coder/irankhub:backend-latest

    - name: Build and push Postgres image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployments/docker/postgres.Dockerfile
        push: true
        tags: josy-coder/irankhub:postgres-latest

    - name: Build and push RabbitMQ image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployments/docker/rabbitmq.Dockerfile
        push: true
        tags: josy-coder/irankhub:rabbitmq-latest

    - name: Set up Kubernetes config
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployments/kubernetes/