name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: josekecha@keemail.me
  DOCKER_PASSWORD: Kristina pimenova1!

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push Backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployments/docker/backend.Dockerfile
        push: true
        tags: josekecha/irankdb-backend:latest

    - name: Build and push Postgres image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployments/docker/postgres.Dockerfile
        push: true
        tags: josekecha/irankdb-postgres:latest

    - name: Build and push RabbitMQ image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployments/docker/rabbitmq.Dockerfile
        push: true
        tags: josekecha/irankdb-rabbitmq:latest

    - name: Set up Kubernetes config
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployments/kubernetes/